### ISSUE TITLE
Option for limiting TA text length, critical for Motorola radios

### ISSUE THREAD

**Issue by yl3im** [g4klx/MMDVMHost#681] opened 2021-03-05 08:25 UTC
Motorola radios have issues with displaying TA text longer than 13 characters. If the text contains non alphanumeric symbols like commas, the radio may misbehave: freezing, rebooting, showing various artifacts on display. The issue is common up to the latest M2020.02 firmware.

Please introduce the option to limit TA text to 13 chars and/or sanitize its contents. I am aware now there already is EmbeddedLCOnly option which turns extended data completely off, but it would be nice to have a better solution with partial displaying of TA data.

Thank you!

**Comment by coder-nyc** [comment] 2021-03-05 08:37
Motorola is aware of this problem and has already solved it in the test version of the firmware T02.20.02.0002, I am using this firmware and can confirm that the problem is no longer relevant. The solution to this bug will be included in the firmware version M2021.1, the release of which was announced by Motorola for the second week of March 2021. In connection with the above, I do not consider it necessary to carry out work on this ticket.

**Comment by g4klx** [comment] 2021-03-05 08:50
They are my feelings to.


Sent from Yahoo Mail for iPhone


On Friday, March 5, 2021, 08:37, coder-nyc <notifications@github.com> wrote:




Motorola is aware of this problem and has already solved it in the test version of the firmware T02.20.02.0002, I am using this firmware and can confirm that the problem is no longer relevant. The solution to this bug will be included in the firmware version M2021.1, the release of which was announced by Motorola for the second week of March 2021. In connection with the above, I do not consider it necessary to carry out work on this ticket.

**Comment by g7npw** [comment] 2021-03-05 17:15
Yes but Motorola will never update firmware for radios over a certain 
age or series so these will never get fixed. It is also these older 
radios that will find there way into the amateur market and are doing so 
now so it was a good idea and request I reckon. Depends how difficult to 
implement I guess.

Just my views.

Dom G7NPW

**Comment by randybuildsthings** [comment] 2021-03-05 17:58
The radios you're referring to can be updated to the most recent firmware (if they are M2020.02). TA can always be disabled in MMDVMHost for those radios that can't cope with it. As an owner of Motorola DMR equipment myself, I understand the desire to interoperate, but it's not solely the problem of @g4klx to accommodate one manufacturers business model/firmware practices, especially when Motorola doesn't make up a majority of the DMR equipment in use on ham DMR networks.

I get that it's frustrating. I just paid $93 for a three year firmware update subscription for my XPR5550e on top of the $170 for three years of MOTOTRBO CPS access. I get it. But it's not Jonathan's job to fix, TBH.

Submit a patch if you think you can figure out how to accommodate this, but I would say there are bigger fish to fry out there in the MMDVM world right now. Cheers

**Closed** 2021-03-07 17:09 UTC
